Adding support for bypassing RootBeer library.
sensepost/objection pull request #463
Opened 2021-06-04 13:01 UTC by haxxinen

<img width="1207" alt="RootBeer bypass via Objection" src="https://user-images.githubusercontent.com/32751905/120805100-afeea500-c545-11eb-8887-a847f325caf8.png">
app: https://github.com/scottyab/rootbeer
lib: https://github.com/scottyab/rootbeer/tree/master/rootbeerlib
apk: https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample
blog: https://medium.com/@scottyab/detecting-root-on-android-97803474f694

2021-06-04 15:23 UTC, leonjza commented
Thank you! Will test this soonest! 🙌

2022-01-10 12:47 UTC, haxxinen commented
@leonjza Fixed conflict. And yes, the obfuscated methods should be predictable enough. Please test when you have the time. Thanks.

2022-01-30 09:51 UTC, leonjza commented
I finally dug into some applications sourced from [here](https://www.appbrain.com/stats/libraries/details/rootbeer/rootbeer) (thanks @CDuPlooy for the hint on the URL mentioned in the Rootbeer project page), and found the obfuscated method names to be unpredictable. There was one pattern I saw repeated though, but I still feel that it is not predictable enough. Eg:

```java
    public boolean n() {
        return j() || h() || b("su") || c() || e() || l() || g() || f() || d();
    }
```

I don't think we're dead in the water here though. In fact, this is a pretty cool case where I think we can enumerate function signatures within `com.scottyab.rootbeer.*` that return booleans, and just hook all of those to return false. That way, no matter then function name, we can have some confidence we'll have good hook coverage.

I propose two things:

1. Let's strip out the obfuscated hooks from this PR, and land the unobfuscated version quickly. (There are plenty of unobfuscated apps out there that will make this a useful contribution). I'll do a small code review in a moment as well.
2. Get another new PR in that focusses on `com.scottyab.rootbeer.*`, enumerating functions that return a boolean, hooking all of them to return false.

2022-01-30 09:54 UTC, leonjza requested changes
To small comments, but refer to the one above this for my suggestion on the obfuscated calls first. Thanks! 🙌

2022-01-30 09:54 UTC, leonjza commented on agent/src/android/root.ts
> +
Looks like `bypassRootBeerObfuscatedC` is never closed here.

2022-01-30 09:54 UTC, leonjza commented on agent/src/android/root.ts
> +        return this.checkForBinary.overload('java.lang.String').call(this);
In all of the added functions, the line that calls the original method is unreachable. In this case, the check for the value of `success` will flow into two blocks that will return, never reaching this line.

2022-02-10 05:03 UTC, leonjza commented
Seems like the SELinux flag is still detected with this PR. Thats okay, I'm going to merge and clean this up. Thanks for the contribution! 🙌 

![image](https://user-images.githubusercontent.com/1148127/153340706-a86cb14e-457b-40c5-87ec-45154a27b4b9.png)

2022-02-10 05:04 UTC, merged

2022-02-10 13:16 UTC, leonjza commented
A quick update, I made some small changes post merging this. Mostly to fix a syntax error, small style changes but more importantly I removed the obfuscated hooks for now. I didn't want that to be a blocker to land this entirely, but if theres some evidence that it will actually be useful (aka. there is common proguard rules that make the function renaming predictable), then we can revisit that.

Thanks again for the contribution.